# Generated by Django 5.2.3 on 2025-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(max_length=255)),
                ('group1', models.CharField(max_length=100)),
                ('group2', models.CharField(max_length=100)),
            ],
        ),
    ]
