# Generated by Django 5.2.3 on 2025-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='group1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='group2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
