# Generated by Django 5.2.3 on 2025-08-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_income_group1_income_group2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='month',
            new_name='date',
        ),
    ]
