# Generated by Django 5.2.3 on 2025-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_month_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='subcategory',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
