# Generated by Django 5.2.3 on 2025-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budget_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='income',
            name='group2',
        ),
        migrations.AddField(
            model_name='income',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('INTEREST', 'Interest'), ('RENTAL', 'Rental'), ('GIFT', 'Gift'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
