# Generated by Django 5.2.3 on 2025-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_income_group1_remove_income_group2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='group1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
