# Generated by Django 5.2.3 on 2025-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_expense_group1_alter_expense_group2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='group1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=80),
        ),
    ]
