# Generated by Django 5.2.3 on 2025-09-08 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_budget_created_at_income_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='group2',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date_received',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='group1',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, default='Expense', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
