# Generated by Django 5.2.3 on 2025-09-08 09:39

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_group2_expense_category_and_more'),
    ]

    operations = [
        # Ensure Django tracks these attributes; no renames needed now.
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=80, default="", blank=True),
        ),
    ]
